### ISSUE TITLE
Cod4x

### ISSUE THREAD

**Issue by kill3ill** [miltann/b3-plugin-discord#5]
Hey ,

I run a cod4x server and it seems it doesn't work on it? Can u help me please?

Thanks,

bill :)

**Comment by miltann** [comment]
Whats the issue? Could you post b3 logs or error messages you get? Make sure you follow the installation instructions.

**Comment by kill3ill** [comment]
hey Miltann, thanks for your reply.Irun a cod4x  New Experience server, sorry but i'm a bit noob with all that. 
B3 seems to run good but when i type !report it says "unrecognized command report". It seems command is not active. I tried to follow every step but noway.

KB

**Comment by kill3ill** [comment]
It says "unrecognised command report". I run cod4x new experience server.
Thanks for your help
Kb

**Comment by miltann** [comment]
Which B3 version do you have? In your B3 installation you should find a file called b3.log, could you post that file here?

**Comment by kill3ill** [comment]
B3 version is  v.1.10.6

**Comment by kill3ill** [comment]
B3 is 1.10.6
here  is my B3 log

**Comment by kill3ill** [comment]
Hey,

Did  you received my file gamelog?

**Comment by miltann** [comment]
No, unfortunately you havent posted your b3.log here.

**Comment by kill3ill** [comment]
i sent it to you by mail when you ask me.
Here  it is ,

**Comment by miltann** [comment]
Apparently it doesnt work by mail, please send it directly on github or use pastebin.com.

**Comment by kill3ill** [comment]
ok sorry,
here it is
[net2ftp-1586204889.zip](https://github.com/miltann/b3-plugin-discord/files/4477525/net2ftp-1586204889.zip)

**Comment by miltann** [comment]
Can you restart your b3 installation and send me the b3.log of that?

**Comment by kill3ill** [comment]
Do youmean restarting B3 program?

**Comment by miltann** [comment]
Yes, please restart B3 and then wait until its fully loaded. Then post your b3.log here

**Comment by kill3ill** [comment]
Ok I'll do it when I'm back home, thanks

**Comment by kill3ill** [comment]
here it is :)

[b3.log](https://github.com/miltann/b3-plugin-discord/files/4483713/b3.log)

**Comment by miltann** [comment]
Did you add the discord plugin to your config?

**Comment by kill3ill** [comment]
yes i added it. I think i followed every steps you mentionned. Sorry i'm a bit noob with it, i hope i didn't  miss something.

**Comment by miltann** [comment]
The instructions are working for me and I haven't had any complaints about it. Please recheck/redo every step and check for typing errors.

**Comment by oldtaylor** [comment]
Im doing this first time can you tell me, where exactly to Put my webhook in this code?

		<set name="webhook">enter your webhook here</set>

**Comment by miltann** [comment]
Replace "enter your webhook here" with your webhook link...

**Comment by oldtaylor** [comment]
Thnx!, But in the discord.py it says in the Problems - Unable to import b3 pylint(import-error)

**Comment by miltann** [comment]
Where do you get this error?
