### ISSUE TITLE
Can not find configuration file

### ISSUE THREAD

**Issue by donna30urt** [miltann/b3-plugin-discord#6]
Heya, I'm trying to install this plugin for the bigbrotherbot on my urbanterror server, I've followed your instructions however b3 is giving me the following output:

`200520 22:49:10 VERBOSE  'Discord is not a built-in plugin (No module named discord)'
200520 22:49:10 VERBOSE  u'Trying external plugin directory : /home/urt2/big-brother-bot-1.12/b3/extplugins'
200520 22:49:10 WARNING  u'Could not find specified configuration file /home/urt2/big-brother-bot-1.12/b3/extplugins/conf/discord.xml for plugin discord'
200520 22:49:10 ERROR    'Could not load plugin discord'
Traceback (most recent call last):
  File "/home/urt2/big-brother-bot-1.12/b3/parser.py", line 704, in loadPlugins
    cfg = _get_plugin_config(p['name'], clz, p['conf'])
  File "/home/urt2/big-brother-bot-1.12/b3/parser.py", line 681, in _get_plugin_config
    raise b3.config.ConfigFileNotFound('plugin %s cannot be loaded without a configuration file' % p_name)
ConfigFileNotFound: 'plugin discord cannot be loaded without a configuration file'`

**Comment by miltann** [comment]
It seems like your B3 installation is looking for the configuration file in a different folder than specified. Try to put the configuration file in b3/extplugins instead of b3/extplugins/conf.
